[tool.poetry]
name = "viz"
version = "0.1.0"
description = ""
authors = ["John Horton"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^3.0.2"
rich = "^13.9.4"
levenshtein = "^0.26.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
